version: "3"
volumes:
   appdata: ~
services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports :
     - "80:80"
    volumes:
     - ./:/var/www/html/
     - appdata:/var/www/html/var/cache
     - appdata:/var/www/html/var/logs
     - .:/var/www/html:cached
    working_dir: /var/www/html
    links:
     - database
    container_name: symfonyApp
  database:
      image: mysql:5.7
      ports:
       - "3306:3306"
      volumes:
       - ./database:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=Mydb
      container_name: symfonyDb
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports :
      - "8090:80"
     environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
     links:
      - database:db
     container_name: symfonyMysql